config/routes.rb
InitialRelease::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users
  
  mount Ckeditor::Engine => '/ckeditor'
  
  root :to => 'Articles#index'

  resources :articles, :galeries

end

app/models/article.rb
#encoding: utf-8
class Article < ActiveRecord::Base
  #attr_accessible :title, :body

  #before_save :set_permalink
  validates :title, :presence => :true
  #permalink :title, :to_param => %w(id permalink)

  acts_as_nested_set

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]
  
  #def to_label
  #  self.title
  #end

  #private
  #  
  #  def set_permalink
  #    self.permalink = Russian.translit(self.title).mb_chars.downcase.gsub(/[^0-9а-яa-z]+/, ' ').strip.gsub(' ', '-').to_s
  #  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"
  
  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_presence :data

  def url_content
    url(:content)
  end
end

app/models/galery.rb
#encoding: utf-8
class Galery < ActiveRecord::Base

  validates_presence_of :name
  
  has_many :galery_photos
  has_many :photos, :through => :galery_photos

  belongs_to :photo

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

end

app/models/galery_photo.rb
#encoding: utf-8
class GaleryPhoto < ActiveRecord::Base

  belongs_to :photo
  belongs_to :galery

end

app/models/photo.rb
#encoding: utf-8

require 'paperclip_processors/watermark'

class Photo < ActiveRecord::Base

  validates :name, :presence => true

  has_many :galery_photos
  has_many :galeries, :through => :galery_photos

  image_url = "/system/photo_images/:id/:style/:basename.:extension"
  image_path = ":rails_root/public/system/photo_images/:id/:style/:basename.:extension"

  has_attached_file :photo_image, :processors => [:watermark], :styles => { :medium => { :geometry => "640x480>", :watermark_path => "#{Rails.root}/public/images/watermark.png"} , :thumb => "150x120#" }, url: image_url, path: image_path

  cattr_reader :per_page
  @@per_page = 27

  def self.paginate_galery(galery, page)
    paginate :per_page => 27, :page => page, :order => 'created_at DESC'
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base  
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  
  def index
    @article = Article.find 1
    render action:'show'
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/galeries_controller.rb
class GaleriesController < ApplicationController
	def show
		@galery = Galery.find(params[:id])
		#render :text => 'index'
	end
end

app/controllers/users_controller.rb
class UserController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/show.html.haml
%h2= @article.title
!= @article.body
- if @article.children != []
	- content_for :post do
		- @article.children.each do |art|
			.date
				%span= I18n.l(art.updated_at.to_date, :format => :month)
				28
			.title
				%h3.navigate
					= link_to truncate(art.title, :ommission => '...', :length => 50), article_path(art), :title => art.title
			%div{:style=>"clear:both; margin: 10px; height: 10px;"}
				-#.postdata
				-#	%span.category
				-#		Категория:
				-#		= link_to art.title, article_path(@article)
				-#	-#%span.comments
				-#	-#<a href="http://xtemplate.ru/prosmotr/?p=1#comments" title="Комментарий к записи Привет, мир!">19 Комментариев &#187;</a></span></div>

app/views/galeries/show.html.haml
%h2= @galery.name
.galery_list
	- @galery.photos.each do |photo|
		= link_to image_tag(photo.photo_image.url(:thumb), alt: photo.name), photo.photo_image.url(:medium), title: photo.name, rel: 'gallery', class: 'fancybox'

app/views/layouts/application.html.haml
!!!
%html{:dir => "ltr", :lang => "ru-RU", :xmlns => "http://www.w3.org/1999/xhtml"}
  %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
  %title Детский сад № 140
  = stylesheet_link_tag 'application', :media => "all"
  = javascript_include_tag "application"
  = javascript_include_tag params[:controller]
  %body
    #main-container.grade-kindergarten
      #header
        %h1 Муниципальное бюджетное дошкольное образовательное учреждение
        %h1 "Детский сад общеразвивающего вида №140"
      #content
        #mid-container
          #mininav-wrap
            #grade-mininav
              %ul
                %li.kindergarten= link_to ' ', '#'
                %li.first= link_to ' ', '#'
                %li.second= link_to ' ', '#'
                %li.third= link_to ' ', '#'
                %li.fourth= link_to ' ', '#'
                %li.fifth= link_to ' ', '#'
            #med-rectad
              %ul
                %li
                  %h2 Страницы и разделы сайта
                  %ul
                    - Article.roots.each do |art|
                      %li= link_to art.title, art
                %li
                  %h2 Галлерея фотографий
                  %ul
                    - Galery.all.each do |gal|
                      %li= link_to gal.name, galery_path(gal)
            .clear
        #game-sections
          #section-letters
            #section-letters-top
            #section-letters-mid
              = yield
              .clear
            #section-letters-bot
    .footer
      %br
        %br
          %ul.footer-nav
            %li Создание и продвижение сайтов в Воронеже
            %li.middot •
            %li= link_to 'ARTLevelDesign', 'http://mlip.ru', title: 'Создание и продвижение сайтов в Воронеже: http://mlip.ru'

app/views/users/index.html.haml
%h1 MainPage
%p Find me in app/views/home/index.html.haml